feat: sbom (#88)

diff --git a/builder-ghcr/.github/workflows/pr-open.yml b/builder-ghcr/.github/workflows/pr-open.yml
--- a/builder-ghcr/.github/workflows/pr-open.yml
+++ b/builder-ghcr/.github/workflows/pr-open.yml
@@ -7,11 +7,14 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+permissions:
+  attestations: write
+  id-token: write
+  packages: write
+
 jobs:
   # QuickStart apps build from the same dirs as their Dockerfiles
   build:
-    permissions:
-      packages: write
     name: Build
     runs-on: ubuntu-24.04
     steps:
@@ -35,8 +38,6 @@ jobs:
   # Anything can be retagged if a fallback image exists (e.g. test)
   retag:
     needs: [build]
-    permissions:
-      packages: write
     name: Retag
     runs-on: ubuntu-24.04
     steps:
@@ -60,10 +61,38 @@ jobs:
             exit 1
           fi
 
+  # No attestation, no id-token, no build
+  no-attestation:
+    needs: [build]
+    name: No Attestation
+    permissions:
+      attestations: none
+      id-token: none
+      packages: write
+    runs-on: ubuntu-24.04
+    steps:
+      - uses: actions/checkout@v4
+      - id: no-attestation
+        uses: ./
+        with:
+          package: backend
+          keep_versions: 10
+          repository: bcgov/quickstart-openshift
+          tags: ${{ github.event.number }}-no-attestation
+          tag_fallback: test
+          triggers: ('backend/')
+
+      - if: steps.no-attestation.outputs.triggered != 'false'
+        run: |
+          # Verify outputs
+          echo "Outputs: ${{ toJSON(steps.no-attestation.outputs) }}"
+          if [ -z "${{ steps.no-attestation.outputs.digest }}" ] || [ "${{ steps.no-attestation.outputs.triggered }}" != "true" ]; then
+            echo "Error!  Verify outputs."
+            exit 1
+          fi
+
   # FOM apps build from repo root, above their Dockerfiles (extra params)
   advanced:
-    permissions:
-      packages: write
     name: Advanced
     runs-on: ubuntu-24.04
     steps:
@@ -89,32 +118,13 @@ jobs:
             echo "Error!  Verify outputs."
             exit 1
           fi
-  # FOM apps build from repo root, above their Dockerfiles (extra params)
-  uppercase:
-    permissions:
-      packages: write
-    name: Uppercase
+
+  results:
+    name: PR Results
+    needs: [advanced, build, no-attestation, retag]
+    if: always()
     runs-on: ubuntu-24.04
     steps:
-      - uses: actions/checkout@v4
-      - id: advanced
-        uses: ./
-        with:
-          package: api
-          build_context: ./api
-          build_file: api/Dockerfile
-          keep_versions: 10
-          repository: bcgov/NRPTI
-          tags:
-            ${{ github.event.number }}-test
-            ${{ github.event.number }}-multiline
-            pr-latest
-
-      - if: steps.advanced.outputs.triggered != 'false'
-        run: |
-          # Verify outputs
-          echo "Outputs: ${{ toJSON(steps.advanced.outputs) }}"
-          if [ -z "${{ steps.advanced.outputs.digest }}" ]|| [ "${{ steps.advanced.outputs.triggered }}" != "true" ]; then
-            echo "Error!  Verify outputs."
-            exit 1
-          fi
+      - if: contains(needs.*.result, 'failure')||contains(needs.*.result, 'canceled')
+        run: echo "At least one job has failed." && exit 1
+      - run: echo "Success!"
