feat: shorten Docker image paths (repo=package) (#93)

diff --git a/builder-ghcr/action.yml b/builder-ghcr/action.yml
--- a/builder-ghcr/action.yml
+++ b/builder-ghcr/action.yml
@@ -66,23 +66,11 @@ outputs:
 runs:
   using: composite
   steps:
-    # Cleanup if inputs.keep_versions provided
-    - name: GHCR Cleanup
-      if: inputs.keep_versions
-      continue-on-error: true # Stop fail if no versions to delete
-      uses: actions/delete-package-versions@v5.0.0
-      with:
-        package-name: "${{ github.event.repository.name }}/${{ inputs.package }}"
-        package-type: "container"
-        min-versions-to-keep: ${{ inputs.keep_versions }}
-        ignore-versions: "${{ inputs.keep_regex }}"
-
     - id: vars
       shell: bash
       env:
-        INPUT_BUILD_CONTEXT: ${{ inputs.build_context }}
-        INPUT_BUILD_FILE: ${{ inputs.build_file }}
         INPUT_PACKAGE: ${{ inputs.package }}
+        CONTEXT_REPO: ${{ github.event.repository.name }}
       run: |
         # Process inputs and set variables
         set -euo pipefail
@@ -92,28 +80,29 @@ runs:
           echo "Input 'tag' is deprecated. Please use 'tags' instead."
           exit 1
         fi
+        
+        # If package matches repo name, use simpler image_path
+        if [ "${INPUT_PACKAGE,,}" = "${CONTEXT_REPO,,}" ]; then
+          image_path="${{ github.repository }}"
+        else
+          image_path="${{ github.repository }}/${{ inputs.package }}"
+        fi
+        echo "image_path=${image_path,,}" >> $GITHUB_OUTPUT
 
-        # Set build context and file with defaults
-        build_context="${INPUT_BUILD_CONTEXT:-$INPUT_PACKAGE}"
-        build_file="${INPUT_BUILD_FILE:-${build_context}/Dockerfile}"
+        # Comma-separated list (e.g. ghcr.io/org/repo/package:tag1,ghcr.io/org/repo/package:tag2)
+        tags_csv=$(echo "${{ inputs.tags }}" | grep -v '^$' | sed "s|^|ghcr.io/${image_path}:|" | tr '[:upper:]' '[:lower:]' | paste -sd,)
+        echo "tags_csv=${tags_csv}" >> $GITHUB_OUTPUT
 
-        # Process tags into comma-separated list of full image paths (concise version)
-        mapfile -t tags < <(printf '%s\n' "${{ inputs.tags }}" | tr '[:upper:]' '[:lower:]' | tr -d ' ' | grep -v '^$')
-        # make the repository lowercase
-        repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
-        # make the package lowercase
-        package_lower=$(echo "$INPUT_PACKAGE" | tr '[:upper:]' '[:lower:]')
-        tags=("${tags[@]/#/ghcr.io/${repo_lower}/${package_lower}:}")
-        tags_csv=$(IFS=, ; echo "${tags[*]}")
-
-        # Output all variables at once, and verify they are set
-        for v in build_context build_file tags_csv repo_lower package_lower; do
-          if [ -z "${!v}" ]; then
-            echo "Error: $v is not set!" >&2
-            exit 1
-          fi
-          echo "$v=${!v}" >> "$GITHUB_OUTPUT"
-        done
+    # Cleanup if inputs.keep_versions provided
+    - name: GHCR Cleanup
+      if: inputs.keep_versions
+      continue-on-error: true # Stop fail if no versions to delete
+      uses: actions/delete-package-versions@v5.0.0
+      with:
+        package-name: "${{ steps.vars.outputs.image_path }}"
+        package-type: "container"
+        min-versions-to-keep: ${{ inputs.keep_versions }}
+        ignore-versions: "${{ inputs.keep_regex }}"
 
     # Send triggers to diff action
     - id: diff
@@ -125,7 +114,7 @@ runs:
     # Check if a build is required (steps.build.outputs.triggered=true|false)
     - name: Check for builds
       env:
-        URL_FALLBACK: ghcr.io/${{ steps.vars.outputs.repo_lower }}/${{ steps.vars.outputs.package_lower }}:${{ inputs.tag_fallback }}
+        URL_FALLBACK: ghcr.io/${{ steps.vars.outputs.image_path }}:${{ inputs.tag_fallback }}
       id: build
       shell: bash
       run: |
@@ -151,7 +140,7 @@ runs:
       if: steps.build.outputs.triggered != 'true'
       with:
         registry: ghcr.io
-        repository: ${{ steps.vars.outputs.repo_lower }}/${{ steps.vars.outputs.package_lower }}
+        repository: ${{ steps.vars.outputs.image_path }}
         target: ${{ inputs.tag_fallback }}
         tags: |
           ${{ inputs.tags }}
@@ -177,8 +166,8 @@ runs:
       if: steps.build.outputs.triggered == 'true'
       uses: docker/build-push-action@v6
       with:
-        context: ${{ steps.vars.outputs.build_context }}
-        file: ${{ steps.vars.outputs.build_file }}
+        context: ${{ inputs.build_context || inputs.package }}
+        file: ${{ inputs.build_file || format('{0}/Dockerfile', inputs.package) }}
         push: true
         tags: ${{ steps.vars.outputs.tags_csv }}
         cache-from: type=gha
@@ -196,7 +185,7 @@ runs:
       shell: bash
       run: |
         # Generate SBOM in both cyclonedx and spdx formats
-        IMAGE="ghcr.io/${{ steps.vars.outputs.repo_lower }}/${{ steps.vars.outputs.package_lower }}@${{ steps.build_and_push.outputs.digest }}"
+        IMAGE="ghcr.io/${{ steps.vars.outputs.image_path }}@${{ steps.build_and_push.outputs.digest }}"
         
         # Create SBOMs directory
         mkdir -p sboms
@@ -238,10 +227,11 @@ runs:
 
     # Action repo needs to be present for cleanup/tests
     - name: Checkout local repo to make sure action.yml is present
-      if: github.repository != inputs.repository
+      if: github.repository != inputs.repository || failure()
       uses: actions/checkout@v4
 
     - name: Print summary outputs
+      if: always() # Always run this step to summarize the build
       shell: bash
       run: |
         echo "---- Build Summary ----"
